import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import '@/styles/globals.css';
import Header from './_components/header/header';
import Footer from './_components/footer';
import { Toaster } from 'sonner';

const manrope = Manrope({
  variable: '--font-manropeSans',
  subsets: ['latin'],
  weight: ['800', '700', '500', '400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function PublicLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div
      className={`${manrope.variable} antialiased relative min-h-screen grid grid-rows-[auto_1fr_auto] bg-surface-page`}
    >
      {children}
      <Footer />
      <Toaster
        closeButton
        containerAriaLabel='Notifications'
        toastOptions={{
          style: { borderRight: '10px solid var(--color-brand-primary)' },
        }}
      />
    </div>
  );
}
