import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import '@/styles/globals.css';
import Header from './_components/header';
import Footer from './_components/footer';

const manrope = Manrope({
  variable: '--font-manropeSans',
  subsets: ['latin'],
  weight: ['700', '500', '400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function PublicLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div
      className={`${manrope.variable} antialiased relative min-h-[100vh] grid grid-rows-[auto_1fr_auto]`}
    >
      <Header />
      <main className='max-w-(--max-width) mx-auto px-6 md:px-10'>
        {children}
      </main>
      <Footer />
    </div>
  );
}
